language: node_js

node_js:
  - 7
  - 6
  - 5

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm run test
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CI=true

before_deploy:
 - npm install netlify-cli -g
 - npm run build

deploy:
 provider: script
 script: netlify deploy -s f207d25a-9e2b-428f-b799-c0212528d788 -t 82decdc4d875fa61b2febab5cbb094daceb32956d8e74ed5d27bc33759ca7060 -p ./build
 skip_cleanup: true
 on:
   branch: master